# Generated by Django 4.2.2 on 2023-07-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_localservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='localservice',
            name='from_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='localservice',
            name='to_time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
