# Generated by Django 4.2.2 on 2023-07-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_localservice_from_time_localservice_to_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='localservice',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
