# Generated by Django 4.2.2 on 2023-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_localservice_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localservice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
