# Generated by Django 4.2.2 on 2023-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remoteservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remoteservice',
            name='location',
        ),
        migrations.AlterField(
            model_name='localservice',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
