# Generated by Django 4.2.2 on 2023-08-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_localservice_location_localservice_x_cood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='onservicelocal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hire', to='app1.localservice'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
