# Generated by Django 4.2.2 on 2023-08-04 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_usermodels_onservicelocal_alter_usermodels_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='onserviceglobal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hire_remote', to='app1.remoteservice'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='onservicelocal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_hire_local', to='app1.localservice'),
        ),
    ]
