# Generated by Django 4.2.2 on 2023-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_usermodels_globalservicefrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='x_cood',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='y_cood',
            field=models.FloatField(default=None, null=True),
        ),
    ]
