# Generated by Django 4.2.2 on 2023-08-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_usermodels_x_cood_alter_usermodels_y_cood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='globalServiceFrom',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='globalServiceTo',
        ),
    ]
