# Generated by Django 4.2.2 on 2023-08-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_usermodels_globalservicefrom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='globalServiceFrom',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='globalServiceTo',
        ),
    ]
