# Generated by Django 4.2.2 on 2023-08-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_usermodels_globalservicefrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='globalServiceTo',
        ),
        migrations.RemoveField(
            model_name='usermodels',
            name='localServiceTo',
        ),
        migrations.AddField(
            model_name='usermodels',
            name='globalServiceDuration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='localServiceDuration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
