# Generated by Django 4.2.2 on 2023-08-11 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_usermodels_onserviceglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='onserviceglobal',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_hire_remote', to='app1.remoteservice'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='onservicelocal',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_hire_local', to='app1.localservice'),
        ),
    ]
