# Generated by Django 4.2.2 on 2023-08-11 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_usermodels_onserviceglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='onservicelocal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.localservice'),
        ),
    ]
