# Generated by Django 4.2.2 on 2023-08-11 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_usermodels_onservicelocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='onserviceglobal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.remoteservice'),
        ),
    ]
