# Generated by Django 4.2.2 on 2023-08-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_usermodels_onserviceglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='onserviceglobal',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.remoteservice'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='onservicelocal',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.localservice'),
        ),
    ]
